### ISSUE TITLE
Добавить CI проверки для новых пулл-реквестов

### ISSUE THREAD

**Issue by avdotion** [avdotion/clue#33]
Требуется добавить минимальные проверки для новых пулл-реквестов, используя встроенный в GitHub функционал. Рекомендуемые проверки:
* Тест сборки
* Тесты eslint
* Тесты jest
* Деплой на GitHub pages

**Comment by laerllik** [comment]
Может заведем для каждого пункта отдельный issue? Так будет легче отслеживать выполненые задачи
